### ISSUE TITLE
An option to generate scoped styles using `:where`

### ISSUE THREAD

**Issue by brc-dd** [vuejs/rfcs#554]
### What problem does this feature solve?

Currently styles are generated like this:

```css
.className[data-v-hash] {
  color: green;
}
```

It would be better if there is some option that can generate styles like this:

```css
.className:where([data-v-hash]) {
  color: green;
}
```

In the above output, the specificity of the selector is preserved.

### What does the proposed API look like?

Some option at config level like:

```ts
// vite.config.ts

export default {
  plugins: [
    vue({
      style: {
        useWhereInAttributeSelectors: true // some better name probably
      }
    })
  ]
}
```
